notifications:
  email: false

dist: focal
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - libopencv-dev
      - libqglviewer-dev-qt5

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel_3.3.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.3.1-linux-x86_64.deb

script:
  - bazel build ...
  - bazel test ...
